function [y1, y2] = sb_coords_an(x)
    y1 = exp(-x).*(-1 - 8.*exp(x)+8.*exp(3.*x)...
        + exp(4.*x) + 12.*exp(2.*x).*x)...
        ./(8.*(1 + exp(x)).^2);

    y2 = exp(-x).*(1+3.*exp(x)+3.*exp(4.*x)+exp(5.*x)...
        -4.*exp(3.*x).*(-7+3.*x) +4.*exp(2.*x).*(7+3.*x))...
        ./(8.*(1 + exp(x)).^3);
end