function symDF = JacSH_toMerge(x1,params)

p1 = params.mu;
p2 = params.nu;
%JACSH
%    SYMDF = JACSH(P1,P2,X1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    28-Nov-2020 15:05:06

symDF = reshape([0.0,0.0,0.0,-p1+p2.*x1.*2.0-x1.^2.*3.0-1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,-2.0,0.0,0.0,1.0,0.0],[4,4]);
