function totalhessian = BigHessSH(x1,p2)
%BIGHESSSH
%    TOTALHESSIAN = BIGHESSSH(P2,X1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    28-Nov-2020 15:10:54

totalhessian = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,p2.*2.0-x1.*6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[16,4]);
